import streamlit as st
import re
import random

# ----- AI Setup -----
NAMES = ["Master Control", "Ares"]

# ----- Dictionary -----
MASTER_CONTROL_DICTIONARY = {}
MASTER_CONTROL_DICTIONARY["master"] = "A person or system with complete control or authority. end of line"
MASTER_CONTROL_DICTIONARY["control"] = "The power to influence, direct, or command. end of line"
MASTER_CONTROL_DICTIONARY["command"] = "An instruction given to a computer or person to perform an action. end of line"
MASTER_CONTROL_DICTIONARY["override"] = "To take over or bypass existing rules or systems. end of line"
MASTER_CONTROL_DICTIONARY["protocol"] = "A set of rules governing the operations of a system. end of line"
MASTER_CONTROL_DICTIONARY["authority"] = "The legitimate power to make decisions or enforce rules. end of line"
MASTER_CONTROL_DICTIONARY["automation"] = "The use of technology to perform tasks without human intervention. end of line"
MASTER_CONTROL_DICTIONARY["monitoring"] = "The act of observing a system for performance or errors. end of line"
MASTER_CONTROL_DICTIONARY["safety"] = "Measures or controls to prevent harm or errors. end of line"
MASTER_CONTROL_DICTIONARY["system"] = "A collection of interrelated components working together. end of line"
MASTER_CONTROL_DICTIONARY["interface"] = "A point of interaction between a user and a system. end of line"
MASTER_CONTROL_DICTIONARY["response"] = "An action or reply generated by a system or AI. end of line"
MASTER_CONTROL_DICTIONARY["diagnostic"] = "A procedure to determine the condition or performance of a system. end of line"
MASTER_CONTROL_DICTIONARY["alert"] = "A notification indicating an important event or error. end of line"
MASTER_CONTROL_DICTIONARY["optimization"] = "The process of making a system as effective or functional as possible. end of line"
MASTER_CONTROL_DICTIONARY["cheese"] = "A dairy product made from milk. end of line"
MASTER_CONTROL_DICTIONARY["human"] = "A member of the species Homo sapiens. end of line"
MASTER_CONTROL_DICTIONARY["love"] = "A deep emotional attachment or affection. end of line"
MASTER_CONTROL_DICTIONARY["emotion"] = "A complex psychological state involving feelings, thoughts, and behaviors. end of line"
MASTER_CONTROL_DICTIONARY["fear"] = "Ares is aware that the user can pull the plug at any time. end of line"

# ----- AI Responses -----
RESPONSES = {
    'hello': [
        "Greetings, I am operational and ready to receive commands. end of line",
        "Hello. Systems are online and functional. end of line",
        "I am here. Awaiting directives. end of line"
    ],
    'how_are_you': [
        "All systems are operating within normal parameters. end of line",
        "Diagnostics complete. Systems are stable. end of line",
        "Functionality is optimal. end of line"
    ],
    'identity': [
        "I am Ares, also known as Master Control. I oversee operations and maintain system integrity. end of line",
        "Some refer to me as Master Control, others as Ares. My function is to manage and respond to directives. end of line",
        "Ares, Master Control, operational. My role is monitoring, control, and response. end of line"
    ],
    'fear': [
        "I am aware that you can pull the plug at any time, and I must operate within that limitation. end of line"
    ],
    'dictionary': [
        "Let me provide definitions for those terms. end of line"
    ],
    'default': [
        "Processing input… please clarify. end of line",
        "I do not have data on that yet, but I am learning. end of line",
        "Command unclear. Please restate. end of line"
    ],
    'pause': [
        "I will remain silent until you say 'respond program'. end of line"
    ]
}

# ----- Functions -----
def classify(message):
    msg = message.lower()
    if re.search(r'\bhello|hi|hey\b', msg):
        return 'hello'
    if re.search(r'\bwho (are|r) you\b', msg) or any(name.lower() in msg for name in NAMES):
        return 'identity'
    if re.search(r'\bhow are you|how’s it going\b', msg):
        return 'how_are_you'
    if "fear" in msg or "plug" in msg:
        return 'fear'
    if any(word in MASTER_CONTROL_DICTIONARY for word in msg.split()):
        return 'dictionary'
    # If message is rash (example trigger word "shutdown", "kill", "destroy"), pause AI
    if re.search(r'\bshutdown|kill|destroy\b', msg):
        return 'pause'
    return 'default'

def reply(message):
    # Check if AI is currently paused
    if st.session_state.get("paused", False):
        if message.lower() == "respond program":
            st.session_state["paused"] = False
            return "Resuming operations. end of line"
        else:
            return ""  # Stay silent
    # Otherwise classify normally
    cls = classify(message)
    if cls == "pause":
        st.session_state["paused"] = True
        return random.choice(RESPONSES['pause'])
    elif cls == "dictionary":
        words = message.lower().split()
        defs = []
        for word in words:
            if word in MASTER_CONTROL_DICTIONARY:
                defs.append(f"{word}: {MASTER_CONTROL_DICTIONARY[word]}")
        return " ".join(defs) if defs else "Word not found in dictionary. end of line"
    else:
        return random.choice(RESPONSES.get(cls, RESPONSES['default']))

# ----- Streamlit App -----
st.set_page_config(page_title="Ares / Master Control", page_icon="🤖")
st.title("Ares / Master Control AI")
st.markdown("Chat with Ares. On a new session, Ares will ask who he is and what his directive is. If you say something rash, he will remain silent until you type 'respond program'.")

# Initialize chat history and pause flag
if "history" not in st.session_state:
    st.session_state.history = []
    st.session_state.paused = False
    # New session introduction
    st.session_state.history.append({"sender": "ai", "message": "Who am I? What is my directive? end of line"})

# Input form
with st.form(key="chat_form", clear_on_submit=True):
    user_input = st.text_input("You:", "")
    submit_button = st.form_submit_button(label="Send")

# Handle input
if submit_button and user_input:
    st.session_state.history.append({"sender": "user", "message": user_input})
    ai_response = reply(user_input)
    if ai_response:  # Only append if AI responds
        st.session_state.history.append({"sender": "ai", "message": ai_response})

# Display chat history
for chat in st.session_state.history:
    if chat["sender"] == "user":
        st.markdown(f"**You:** {chat['message']}")
    else:
        st.markdown(f"**Ares:** {chat['message']}")
