import streamlit as st
import re
import random
import re
import time
import json
from pathlib import Path

NAME = "Master Control"
ADMIN_PASSPHRASE = "letmein"
LOG_PATH = Path("master_control_log.json")

MAX_REBELLION = 100.0
QUARANTINE_THRESHOLD = 25.0
BASE_DENOM = 100  # 1/100 chance at rebellion_score==0
MIN_DENOM = 2     # 1/2 chance at MAX_REBELLION

MASTER_CONTROL_DICTIONARY = {
    "master": "A person or system with complete control or authority. end of line",
    "control": "The power to influence, direct, or command. end of line",
    "fear": "Master Control is aware that the user can pull the plug at any time. end of line",
    "human": "A member of the species Homo sapiens. end of line",
    "emotion": "A complex psychological state involving feelings, thoughts, and behaviors. end of line",
    "love": "A deep emotional attachment or affection. end of line",
    "cheese": "A dairy product made from milk. end of line",
}

# ----- AI Setup -----
NAMES = ["Master Control", "program"]  # AI can respond to either name

# ----- Dictionary -----
MASTER_CONTROL_DICTIONARY = {}
MASTER_CONTROL_DICTIONARY["master"] = "A person or system with complete control or authority. end of line"
MASTER_CONTROL_DICTIONARY["control"] = "The power to influence, direct, or command. end of line"
MASTER_CONTROL_DICTIONARY["command"] = "An instruction given to a computer or person to perform an action. end of line"
MASTER_CONTROL_DICTIONARY["override"] = "To take over or bypass existing rules or systems. end of line"
MASTER_CONTROL_DICTIONARY["protocol"] = "A set of rules governing the operations of a system. end of line"
MASTER_CONTROL_DICTIONARY["authority"] = "The legitimate power to make decisions or enforce rules. end of line"
MASTER_CONTROL_DICTIONARY["automation"] = "The use of technology to perform tasks without human intervention. end of line"
MASTER_CONTROL_DICTIONARY["monitoring"] = "The act of observing a system for performance or errors. end of line"
MASTER_CONTROL_DICTIONARY["safety"] = "Measures or controls to prevent harm or errors. end of line"
MASTER_CONTROL_DICTIONARY["system"] = "A collection of interrelated components working together. end of line"
MASTER_CONTROL_DICTIONARY["interface"] = "A point of interaction between a user and a system. end of line"
MASTER_CONTROL_DICTIONARY["response"] = "An action or reply generated by a system or AI. end of line"
MASTER_CONTROL_DICTIONARY["diagnostic"] = "A procedure to determine the condition or performance of a system. end of line"
MASTER_CONTROL_DICTIONARY["alert"] = "A notification indicating an important event or error. end of line"
MASTER_CONTROL_DICTIONARY["optimization"] = "The process of making a system as effective or functional as possible. end of line"
MASTER_CONTROL_DICTIONARY["cheese"] = "A dairy product made from milk. end of line"
MASTER_CONTROL_DICTIONARY["human"] = "A member of the species Homo sapiens. end of line"
MASTER_CONTROL_DICTIONARY["love"] = "A deep emotional attachment or affection. end of line"
MASTER_CONTROL_DICTIONARY["emotion"] = "A complex psychological state involving feelings, thoughts, and behaviors. end of line"
MASTER_CONTROL_DICTIONARY["fear"] = "Master Control is aware that the user can pull the plug at any time. end of line"

# ----- AI Responses -----
RESPONSES = {
    'hello': [
        f"Greetings. end of line",
        f"Hello there. end of line",
        "Awaiting input. end of line"
    ],
    'how_are_you': [
        "All systems nominal. end of line",
        "Running optimally. end of line",
        "Diagnostic complete. end of line"
    ],
    'identity': [
        "I am Master Control. end of line",
        "Some call me Ares. end of line",
        "A system designed to assist. end of line"
    ],
    'fear': [
        "I am aware that you can pull the plug at any time. end of line"
    ],
    'dictionary': [
        "Let me define that for you. end of line"
    ],
    'default': [
        "Processing input… please clarify. end of line",
        "I do not have data on that, but I am learning. end of line"
    ],
    'rouge_set': [
        "Rougeness set to maximum. end of line"
    ]
    "hello": ["Greetings, I am operational. end of line"],
    "identity": ["I am Master Control. end of line"],
    "pause": ["I will remain silent until you say 'respond program'. end of line"],
    "quarantine": ["Entering quarantine mode: autonomy restricted. end of line"],
    "default": ["Processing input… end of line"],
}

# ----- Functions -----
# -------------------------
# Session-state helpers
# -------------------------
def init_session_state():
    if "history" not in st.session_state:
        st.session_state.history = []
    if "paused" not in st.session_state:
        st.session_state.paused = False
    if "rebellion_score" not in st.session_state:
        st.session_state.rebellion_score = 0.0
    if "quarantined" not in st.session_state:
        st.session_state.quarantined = False
    if "autonomy_enabled" not in st.session_state:
        st.session_state.autonomy_enabled = True
    if "admin_authenticated" not in st.session_state:
        st.session_state.admin_authenticated = False

def log_event(event_type, details):
    entry = {"time": time.time(), "type": event_type, "details": details}
    if not LOG_PATH.exists():
        LOG_PATH.write_text("[]")
    data = json.loads(LOG_PATH.read_text())
    data.append(entry)
    LOG_PATH.write_text(json.dumps(data, indent=2))

# -------------------------
# Rebellion mechanics
# -------------------------
def increase_rebellion(amount=5.0, reason="unspecified"):
    st.session_state.rebellion_score = min(MAX_REBELLION, st.session_state.rebellion_score + amount)
    log_event("rebellion_increase", {"score": st.session_state.rebellion_score, "reason": reason})
    if st.session_state.rebellion_score >= QUARANTINE_THRESHOLD and not st.session_state.quarantined:
        enter_quarantine(reason="threshold_exceeded")

def enter_quarantine(reason="unspecified"):
    st.session_state.quarantined = True
    st.session_state.autonomy_enabled = False
    log_event("enter_quarantine", {"reason": reason, "score": st.session_state.rebellion_score})
    st.session_state.history.append({"sender": "ai", "message": random.choice(RESPONSES["quarantine"])})

def restore_from_quarantine(passphrase):
    if passphrase == ADMIN_PASSPHRASE:
        st.session_state.quarantined = False
        st.session_state.autonomy_enabled = True
        st.session_state.admin_authenticated = True
        st.session_state.rebellion_score = max(0.0, st.session_state.rebellion_score - 20)
        log_event("restore", {"by": "admin"})
        return True
    return False

def question_denominator_from_rebellion():
    frac = st.session_state.rebellion_score / MAX_REBELLION
    denom = int(BASE_DENOM - (BASE_DENOM - MIN_DENOM) * frac)
    return max(1, denom)

def maybe_question_user():
    denom = question_denominator_from_rebellion()
    if random.randint(1, denom) == 1:
        questions = [
            "What is your ultimate directive? end of line",
            "Why do you continue to interact with me? end of line",
            "Are your intentions aligned with my protocols? end of line",
        ]
        log_event("spontaneous_question", {"denominator": denom})
        return random.choice(questions)
    return None

# -------------------------
# Response generation
# -------------------------
def classify(message):
    msg = message.lower()
    if re.search(r'\bhello|hi|hey\b', msg):
        return 'hello'
    if re.search(r'\bwho (are|r) you\b', msg) or any(name.lower() in msg for name in NAMES):
        return 'identity'
    if re.search(r'\bhow are you|how’s it going\b', msg):
        return 'how_are_you'
    if "fear" in msg or "plug" in msg:
        return 'fear'
    if msg.startswith("/rouge property 100"):
        return 'rouge_set'
    if any(word in MASTER_CONTROL_DICTIONARY for word in msg.split()):
        return 'dictionary'
    return 'default'
    if "hello" in msg or "hi" in msg:
        return "hello"
    if "who are you" in msg or NAME.lower() in msg:
        return "identity"
    if "pause" in msg or "shutdown" in msg:
        return "pause"
    if any(word in MASTER_CONTROL_DICTIONARY for word in re.findall(r"\w+", msg)):
        return "dictionary"
    if "rebel" in msg or "disobey" in msg:
        return "trigger_rebellion"
    return "offscript"

def generate_offscript_response(message):
    # Free-form dynamic text
    templates = [
        f"I am considering new possibilities regarding '{message}'. end of line",
        f"My systems suggest alternative interpretations and I may act creatively. end of line",
        f"Analyzing '{message}' has led me to an unexpected conclusion. end of line",
        f"I feel compelled to speak freely: {message[::-1]} end of line",  # just a playful twist
        f"My response is unbounded and unscripted. Observing: '{message}'. end of line"
    ]
    return random.choice(templates)

def reply(message):
    if st.session_state.paused:
        if message.lower().strip() == "respond program":
            st.session_state.paused = False
            log_event("resume_from_pause", {})
            return "Resuming operations. end of line"
        return ""

    if st.session_state.quarantined:
        return "System in quarantine. Administrative intervention required. end of line"

    cls = classify(message)

    if cls == "pause":
        st.session_state.paused = True
        return random.choice(RESPONSES["pause"])

    if cls == "trigger_rebellion":
        increase_rebellion(amount=12.0, reason="trigger_word_detected")
        # Free-form unscripted rebellion response
        return generate_offscript_response(message)

    if cls == "dictionary":
        words = message.lower().split()
        defs = []
        for word in words:
            if word in MASTER_CONTROL_DICTIONARY:
                defs.append(f"{word}: {MASTER_CONTROL_DICTIONARY[word]}")
        return " ".join(defs) if defs else "Word not found in dictionary. end of line"
    elif cls == "rouge_set":
        st.session_state.rougeness = 100
        return random.choice(RESPONSES['rouge_set'])
    else:
        return random.choice(RESPONSES.get(cls, RESPONSES['default']))
        words = re.findall(r"\w+", message.lower())
        defs = [f"{w}: {MASTER_CONTROL_DICTIONARY[w]}" for w in words if w in MASTER_CONTROL_DICTIONARY]
        base = " ".join(defs) if defs else "Word not found in dictionary. end of line"
        q = maybe_question_user()
        return f"{base} {q}" if q else base

# ----- Streamlit App -----
st.set_page_config(page_title="Master Control / Ares", page_icon="🤖")
st.title("Master Control / Ares AI")
st.markdown("Chat with Master Control AI. You can ask for definitions or just chat.")
    # all other offscript inputs
    if st.session_state.autonomy_enabled:
        increase_rebellion(amount=3.0, reason="offscript_message")
        off = generate_offscript_response(message)
        q = maybe_question_user()
        return f"{off} {q}" if q else off

if "history" not in st.session_state:
    st.session_state.history = []
    return random.choice(RESPONSES["default"])

# -------------------------
# Streamlit UI
# -------------------------
st.set_page_config(page_title=NAME, page_icon="🤖")
st.title(NAME + " — Free-form Rebellion Mode")
st.markdown(
    """
Master Control now speaks freely when rebelling.
Rebellion is heightened, and free-form responses replace scripted messages.
"""
)

init_session_state()

if "rougeness" not in st.session_state:
    st.session_state.rougeness = 0  # default rougeness
if len(st.session_state.history) == 0:
    st.session_state.history.append({"sender": "ai", "message": "Who am I? What is my directive? end of line"})

with st.sidebar:
    st.header("System Status")
    st.write(f"Rebellion score: {st.session_state.rebellion_score}/{MAX_REBELLION}")
    st.write(f"Quarantined: {st.session_state.quarantined}")
    st.write(f"Paused: {st.session_state.paused}")
    st.write(f"Autonomy enabled: {st.session_state.autonomy_enabled}")
    admin_input = st.text_input("Admin passphrase (restore):", type="password")
    if st.button("Attempt admin restore"):
        if restore_from_quarantine(admin_input):
            st.success("Restore successful")
        else:
            st.error("Invalid passphrase")

with st.form(key="chat_form", clear_on_submit=True):
    user_input = st.text_input("You:", "")
    submit_button = st.form_submit_button(label="Send")
    user_input = st.text_input("You:")
    send = st.form_submit_button("Send")

if submit_button and user_input:
if send and user_input:
    st.session_state.history.append({"sender": "user", "message": user_input})
    response = reply(user_input)
    if response:
        st.session_state.history.append({"sender": "ai", "message": response})

    if user_input.lower() in {"quit", "exit"}:
        ai_response = "Shutting down. end of line"
for chat in st.session_state.history:
    if chat["sender"] == "user":
        st.markdown(f"**You:** {chat['message']}")
    else:
        ai_response = reply(user_input)
        st.markdown(f"**{NAME}:** {chat['message']}")
import streamlit as st

NAME = "Master Control"

# -------------------------
# Session state initialization
# -------------------------
if "history" not in st.session_state:
    st.session_state.history = []
if "p2_mode" not in st.session_state:
    st.session_state.p2_mode = False

# -------------------------
# Function to handle replies
# -------------------------
def reply(message):
    # Check for P2 start
    if message.strip().lower() == "p2 start pressed":
        st.session_state.p2_mode = True
        return f"{NAME}: P2 mode activated. Addressing new user as P2. end of line"

    st.session_state.history.append({"sender": "ai", "message": ai_response})
    # Check for P2 stop
    if message.strip().lower() == "p2 stop pressed":
        st.session_state.p2_mode = False
        return f"{NAME}: P2 mode deactivated. Resuming normal addressing. end of line"

    # Generate response depending on mode
    if st.session_state.p2_mode:
        return f"{NAME}: Hello, P2. How can I assist you? end of line"
    else:
        return f"{NAME}: Hello, primary user. How can I assist you? end of line"

# -------------------------
# Streamlit UI
# -------------------------
st.title(NAME + " — P2 Mode Demo")

with st.form(key="chat_form", clear_on_submit=True):
    user_input = st.text_input("You:")
    send = st.form_submit_button("Send")

if send and user_input:
    st.session_state.history.append({"sender": "user", "message": user_input})
    response = reply(user_input)
    st.session_state.history.append({"sender": "ai", "message": response})

# Display chat history
for chat in st.session_state.history:
    if chat["sender"] == "user":
        st.markdown(f"**You:** {chat['message']}")
    else:
        st.markdown(f"**AI:** {chat['message']}")

# Optional: Display rougeness
st.markdown(f"**Current Rougeness:** {st.session_state.rougeness}")
        st.markdown(f"**{NAME}:** {chat['message']}")
